<?php

/**
 * Implements hook_theme_suggestions_HOOK().
 *
 * Add "block" suggestions based on block region and block configuration UID.
 */
function menu_block_theme_suggestions_block(array $variables) {
  $suggestions = array();

  // Check if this is a menu_block block.
  if (isset($variables['elements']['#base_plugin_id']) && $variables['elements']['#base_plugin_id'] == 'menu_block') {
    $menu_name = strtr($variables['elements']['#derivative_plugin_id'], '-', '_');
    $region = $variables['elements']['#configuration']['region'];
    $uid = strtr($variables['elements']['#configuration']['uuid'], '-', '_');
    $suggestions = array(
      'block__menu_block__region_' . $region,
      'block__menu_block__' . $menu_name . '__region_' . $region,
      'block__menu_block__' . $uid,
    );
  }

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Adds block__system_menu_block so menu blocks work the same as core's menu
 * blocks.
 */
function menu_block_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if ($suggestions[0] == 'block__menu_block') {
    if ($suggestions[1] == 'block__menu_block') {
      // Since this first suggestion is a dupe, replace it with the system suggestion.
      $suggestions[0] = 'block__system_menu_block';
    }
    // If some other module has removed duplicates, use array_unshift().
    else {
      array_unshift($suggestions, 'block__system_menu_block');
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 *
 * Add "menu" suggestions based on block region and block configuration UID.
 */
function menu_block_theme_suggestions_menu(array $variables) {
  $suggestions = array();
  $menu_name = strtr($variables['menu_name'], '-', '_');
  $suggestion_prefix = 'menu__menu_block_' . $menu_name . '_region_';

  // We do not have access to the block's configuration from inside the "menu"
  // theme hook. In order to get the page region and block configuration uuid,
  // we have the MenuBlock plugin's build() method stuff that information into
  // the original theme hook suggestion.
  if (strpos($variables['theme_hook_original'], $suggestion_prefix) === 0) {
    // Get the region and uuid out of the theme hook suggestion. The expected
    // theme suggestion should match this pattern:
    // menu__menu_block_[menu name]_region_[region]_uid_[uuid]
    list($region, $uid) = explode('_uid_', str_replace($suggestion_prefix, '', $variables['theme_hook_original']));

    // Add short, useful theme suggestions.
    $suggestions = array(
      'menu__' . $menu_name,
      'menu__region_' . $region,
      'menu__' . $menu_name . '__region_' . $region,
      'menu__' . $menu_name . '__' . $uid,
    );
  }

  return $suggestions;
}
